//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anima_MJ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Animadb : DbContext
    {
        public Animadb()
            : base("name=Animadb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Art_martiaux> Art_martiaux { get; set; }
        public DbSet<Classe> Classe { get; set; }
        public DbSet<classe_cout> classe_cout { get; set; }
        public DbSet<competence> competence { get; set; }
        public DbSet<Dons> Dons { get; set; }
        public DbSet<histo_charac> histo_charac { get; set; }
        public DbSet<joueur_actu_> joueur_actu_ { get; set; }
        public DbSet<joueur_depense> joueur_depense { get; set; }
        public DbSet<joueur_temp_> joueur_temp_ { get; set; }
        public DbSet<Level> Level { get; set; }
        public DbSet<module_darme> module_darme { get; set; }
        public DbSet<module_joueur> module_joueur { get; set; }
        public DbSet<pouvoir_joueur> pouvoir_joueur { get; set; }
        public DbSet<pouvoir_ki> pouvoir_ki { get; set; }
        public DbSet<temp_charac> temp_charac { get; set; }
        public DbSet<classe_bonus> classe_bonus { get; set; }
        public DbSet<joueur_bonus> joueur_bonus { get; set; }
        public DbSet<joueur_cout> joueur_cout { get; set; }
        public DbSet<Joueur> Joueur { get; set; }
    }
}
