//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anima_MJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class classe_bonus
    {
        public long Id { get; set; }
        public long pv { get; set; }
        public long initiative { get; set; }
        public long di { get; set; }
        public long ppp { get; set; }
        public long charac { get; set; }
        public long attaque { get; set; }
        public long parade { get; set; }
        public long esquive { get; set; }
        public long port_darmure { get; set; }
        public long convoquer { get; set; }
        public long dominer { get; set; }
        public long lier { get; set; }
        public long revoquer { get; set; }
        public long zeon { get; set; }
        public long comp_nat_classe { get; set; }
        public long acrobatie { get; set; }
        public long athletisme { get; set; }
        public long equitation { get; set; }
        public long escalade { get; set; }
        public long natation { get; set; }
        public long saut { get; set; }
        public long impassibilite { get; set; }
        public long prouesse { get; set; }
        public long resistance { get; set; }
        public long observation { get; set; }
        public long pistage { get; set; }
        public long vigilance { get; set; }
        public long animaux { get; set; }
        public long estimation { get; set; }
        public long evaluation_magique { get; set; }
        public long herboristerie { get; set; }
        public long histoire { get; set; }
        public long medecine { get; set; }
        public long memorisation { get; set; }
        public long navigation { get; set; }
        public long occultisme { get; set; }
        public long science { get; set; }
        public long loi { get; set; }
        public long tactique { get; set; }
        public long commandement { get; set; }
        public long intimidation { get; set; }
        public long persuasion { get; set; }
        public long style { get; set; }
        public long commerce { get; set; }
        public long conn_rue { get; set; }
        public long etiquette { get; set; }
        public long camouflage { get; set; }
        public long crochetage { get; set; }
        public long deguisement { get; set; }
        public long discretion { get; set; }
        public long larcin { get; set; }
        public long pieges { get; set; }
        public long poison { get; set; }
        public long art { get; set; }
        public long danse { get; set; }
        public long forge { get; set; }
        public long habilete { get; set; }
        public long musique { get; set; }
        public long orfevrerie { get; set; }
        public long confection { get; set; }
        public long creation_mario { get; set; }
        public long runes { get; set; }
        public long alchimie { get; set; }
        public long animisme { get; set; }
        public long rituel_calligraphie { get; set; }
    }
}
