//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anima_MJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class classe_cout
    {
        public long Id { get; set; }
        public int multi_pv { get; set; }
        public int attaque { get; set; }
        public int parade { get; set; }
        public int esquive { get; set; }
        public int port_darmure { get; set; }
        public int di { get; set; }
        public int ki { get; set; }
        public int accumulation_ki { get; set; }
        public int zeon { get; set; }
        public int multi_amr { get; set; }
        public int projection_magique { get; set; }
        public int convoquer { get; set; }
        public int dominer { get; set; }
        public int lier { get; set; }
        public int revoquer { get; set; }
        public int ppp { get; set; }
        public int projection_psychique { get; set; }
        public int voie_magique { get; set; }
        public int multi_zeon_regen { get; set; }
        public int acrobatie { get; set; }
        public int athletisme { get; set; }
        public int equitation { get; set; }
        public int escalade { get; set; }
        public int natation { get; set; }
        public int saut { get; set; }
        public int impassibilite { get; set; }
        public int prouesse { get; set; }
        public int resistance { get; set; }
        public int observation { get; set; }
        public int pistage { get; set; }
        public int vigilance { get; set; }
        public int animaux { get; set; }
        public int estimation { get; set; }
        public int evaluation_magique { get; set; }
        public int herboristerie { get; set; }
        public int histoire { get; set; }
        public int medecine { get; set; }
        public int memorisation { get; set; }
        public int navigation { get; set; }
        public int occultisme { get; set; }
        public int science { get; set; }
        public int loi { get; set; }
        public int tactique { get; set; }
        public int commandement { get; set; }
        public int intimidation { get; set; }
        public int persuasion { get; set; }
        public int style { get; set; }
        public int commerce { get; set; }
        public int conn_rue { get; set; }
        public int etiquette { get; set; }
        public int camouflage { get; set; }
        public int crochetage { get; set; }
        public int deguisement { get; set; }
        public int discretion { get; set; }
        public int larcin { get; set; }
        public int pieges { get; set; }
        public int poison { get; set; }
        public int art { get; set; }
        public int danse { get; set; }
        public int forge { get; set; }
        public int habilete { get; set; }
        public int musique { get; set; }
        public int orfevrerie { get; set; }
        public int confection { get; set; }
        public int creation_mario { get; set; }
        public int runes { get; set; }
        public int alchimie { get; set; }
        public int animisme { get; set; }
        public int rituel_calligraphie { get; set; }
    }
}
