//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anima_MJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dons
    {
        public long Id { get; set; }
        public string Nom { get; set; }
        public string effet { get; set; }
        public int cout { get; set; }
        public int nombre { get; set; }
        public int droit_daccees { get; set; }
        public string famille { get; set; }
    }
}
