//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anima_MJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joueur
    {
        public long Id_joueur { get; set; }
        public string Pseudo_Joueur { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Classe_level_0 { get; set; }
        public string Sexe { get; set; }
        public string Origine { get; set; }
        public string Classe_social { get; set; }
        public int Age { get; set; }
        public int Apparence { get; set; }
        public int Poid { get; set; }
        public int Hauteur { get; set; }
        public int Taille { get; set; }
        public int base_for { get; set; }
        public int base_agi { get; set; }
        public int base_dex { get; set; }
        public int base_con { get; set; }
        public int base_int { get; set; }
        public int base_per { get; set; }
        public int base_pou { get; set; }
        public int base_vol { get; set; }
        public int total_xp { get; set; }
    }
}
