//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anima_MJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public long Id { get; set; }
        public int id_joueur { get; set; }
        public int level1 { get; set; }
        public string classe { get; set; }
        public int pf_restant { get; set; }
        public int di_restant { get; set; }
        public int ppp_restant { get; set; }
        public int charac { get; set; }
        public int char_nat { get; set; }
        public int comp_nat { get; set; }
    }
}
