//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anima_MJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_charac
    {
        public long Id { get; set; }
        public int id_joueur { get; set; }
        public int Forca { get; set; }
        public int agi { get; set; }
        public int dex { get; set; }
        public int con { get; set; }
        public int inte { get; set; }
        public int per { get; set; }
        public int pou { get; set; }
        public int vol { get; set; }
    }
}
